rnaseq:
  N72:
    fwd: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN72_RunId008_LaneId1/N72_S13_R1_001.fastq.gz
    rev: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN72_RunId008_LaneId1/N72_S13_R2_001.fastq.gz
  N70:
    fwd: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN70_RunId008_LaneId1/N70_S12_R1_001.fastq.gz
    rev: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN70_RunId008_LaneId1/N70_S12_R2_001.fastq.gz
  N44:
    fwd: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN44_RunId008_LaneId1/N44_S11_R1_001.fastq.gz
    rev: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN44_RunId008_LaneId1/N44_S11_R2_001.fastq.gz
  N39:
    fwd: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN39_RunId008_LaneId1/N39_S10_R1_001.fastq.gz
    rev: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN39_RunId008_LaneId1/N39_S10_R2_001.fastq.gz
  N38:
    fwd: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN38_RunId008_LaneId1/N38_S9_R1_001.fastq.gz
    rev: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN38_RunId008_LaneId1/N38_S9_R2_001.fastq.gz
  N34:
    fwd: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN34_RunId008_LaneId1/N34_S8_R1_001.fastq.gz
    rev: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN34_RunId008_LaneId1/N34_S8_R2_001.fastq.gz
  N27:
    fwd: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN27_RunId008_LaneId1/N27_S7_R1_001.fastq.gz
    rev: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN27_RunId008_LaneId1/N27_S7_R2_001.fastq.gz
  N26:
    fwd: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN26_RunId008_LaneId1/N26_S6_R1_001.fastq.gz
    rev: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN26_RunId008_LaneId1/N26_S6_R2_001.fastq.gz
  N10:
    fwd: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN10_RunId008_LaneId1/N10_S5_R1_001.fastq.gz
    rev: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN10_RunId008_LaneId1/N10_S5_R2_001.fastq.gz
  N6:
    fwd: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN6_RunId008_LaneId1/N6_S4_R1_001.fastq.gz
    rev: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN6_RunId008_LaneId1/N6_S4_R2_001.fastq.gz
  N5:
    fwd: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN5_RunId008_LaneId1/N5_S3_R1_001.fastq.gz
    rev: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN5_RunId008_LaneId1/N5_S3_R2_001.fastq.gz
  N4:
    fwd: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN4_RunId008_LaneId1/N4_S2_R1_001.fastq.gz
    rev: /ebio/abt6_sra/years/2021/12_14/karyocode_rnaseq/illumina_VH00745_flowcellAAAJJJCHV_SampleIdN4_RunId008_LaneId1/N4_S2_R2_001.fastq.gz
  lstr_yy:
    fwd: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10512997_1.fastq.gz
    rev: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10512997_2.fastq.gz
  rema_yy:
    fwd: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10512996_1.fastq.gz
    rev: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10512996_2.fastq.gz
  bame_yy:
    fwd: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10512973_1.fastq.gz
    rev: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10512973_2.fastq.gz
  anig_yy:
    fwd: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10512978_1.fastq.gz
    rev: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10512978_2.fastq.gz
  trac_yy:
    fwd: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10512994_1.fastq.gz
    rev: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10512994_2.fastq.gz
  gsin_yy:
    fwd: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10513005_1.fastq.gz
    rev: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10513005_2.fastq.gz
  sroe_yy:
    fwd: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10513009_1.fastq.gz
    rev: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10513009_2.fastq.gz
  gacu_yy:
    fwd: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10513007_1.fastq.gz
    rev: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10513007_2.fastq.gz
  lx13_yy:
    fwd: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10512999_1.fastq.gz
    rev: /ebio/abt2_projects/ag-swart-karyocode/data/sra/SRR10512999_2.fastq.gz

pfam_db: /ebio/abt2_projects/ag-swart-loxodes/db/pfam/Pfam-A.hmm
